import Head from 'next/head'
import BlogPosts from './Components/BlogPosts'
import Header from './Components/Header'
import Slider from './Components/Slider'


export default function Home () {
  return (
    <div>
      <Head>
        <title>Dotgfx</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Slider />
      <BlogPosts />

    </div>
  )
}
